# Generated by Django 4.2.2 on 2023-08-22 11:37

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default=1, upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
