# Generated by Django 4.2.2 on 2023-09-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_review_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='save',
            field=models.BooleanField(default=False),
        ),
    ]
