# Generated by Django 4.2.2 on 2023-09-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_review_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='save',
        ),
    ]
