# Generated by Django 4.2.2 on 2023-09-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_review_rating_alter_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
